name: Motarjm
channels:
  - defaults
dependencies:
    - python=3.13
    - pip:
      - aistudio-sdk==0.3.8
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arabic-reshaper==3.0.0
      - bce-python-sdk==0.9.55
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.10.5
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cssselect==1.3.0
      - cssutils==2.11.1
      - cycler==0.12.1
      - doclayout-yolo==0.0.4
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fastapi==0.119.1
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==1.2.2
      - idna==3.11
      - imagesize==1.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==1.1.3
      - langchain-core==1.1.3
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.15
      - langsmith==0.4.59
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - modelscope==1.33.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - myapplication==0.1.0
      - networkx==3.6.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - orjson==3.11.5
      - ormsgpack==1.12.0
      - packaging==25.0
      - paddleocr==3.3.2
      - paddlepaddle==3.2.2
      - paddlex==3.3.11
      - pandas==2.3.3
      - pillow==12.0.0
      - premailer==3.10.0
      - prettytable==3.17.0
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyclipper==1.4.0
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pymupdf==1.26.6
      - pyparsing==3.2.5
      - pypdfium2==5.1.0
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - reportlab==4.4.6
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.48.0
      - stringzilla==4.4.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.6.1
      - uuid-utils==0.12.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - zstandard==0.25.0
